name: my_humor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  auto_route: ^9.2.2
  get_it: ^8.0.2
  freezed_annotation: ^2.4.4
  sqflite: ^2.3.2
  path_provider: ^2.1.4
  path: ^1.9.0
  fl_chart: ^0.69.0
  pdf: ^3.11.1
  printing: ^5.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
