name: my_humor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  auto_route: ^11.1.0
  get_it: ^9.2.0
  freezed_annotation: ^3.1.0
  sqflite: ^2.3.2
  path_provider: ^2.1.4
  path: ^1.9.0
  fl_chart: ^1.1.1
  pdf: ^3.11.1
  printing: ^5.13.2
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^3.2.5
  auto_route_generator: ^10.5.0

flutter:
  uses-material-design: true
